<?php

/**
 * BaseBibTaxrefRangs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_rang
 * @property string $nom_rang
 * 
 * @method string         get()         Returns the current record's "id_rang" value
 * @method string         get()         Returns the current record's "nom_rang" value
 * @method BibTaxrefRangs set()         Sets the current record's "id_rang" value
 * @method BibTaxrefRangs set()         Sets the current record's "nom_rang" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibTaxrefRangs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.bib_taxref_rangs');
        $this->hasColumn('id_rang', 'string', 4, array(
             'type' => 'string',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom_rang', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}