<?php

/**
 * BaseCorCritereListe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_critere_cf
 * @property integer $id_liste
 * @property BibListes $BibListes
 * @property BibCriteresCf $BibCriteresCf
 * 
 * @method integer         get()              Returns the current record's "id_critere_cf" value
 * @method integer         get()              Returns the current record's "id_liste" value
 * @method BibListes       get()              Returns the current record's "BibListes" value
 * @method BibCriteresCf   get()              Returns the current record's "BibCriteresCf" value
 * @method CorCritereListe set()              Sets the current record's "id_critere_cf" value
 * @method CorCritereListe set()              Sets the current record's "id_liste" value
 * @method CorCritereListe set()              Sets the current record's "BibListes" value
 * @method CorCritereListe set()              Sets the current record's "BibCriteresCf" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorCritereListe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactfaune.cor_critere_liste');
        $this->hasColumn('id_critere_cf', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_liste', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibListes', array(
             'local' => 'id_liste',
             'foreign' => 'id_liste'));

        $this->hasOne('BibCriteresCf', array(
             'local' => 'id_critere_cf',
             'foreign' => 'id_critere_cf'));
    }
}