<?php

/**
 * BaseBibPhenologies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codepheno
 * @property string $pheno
 * @property Doctrine_Collection $TApresence
 * 
 * @method integer             getCodepheno()  Returns the current record's "codepheno" value
 * @method string              getPheno()      Returns the current record's "pheno" value
 * @method Doctrine_Collection getTApresence() Returns the current record's "TApresence" collection
 * @method BibPhenologies      setCodepheno()  Sets the current record's "codepheno" value
 * @method BibPhenologies      setPheno()      Sets the current record's "pheno" value
 * @method BibPhenologies      setTApresence() Sets the current record's "TApresence" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibPhenologies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('florepatri.bib_phenologies');
        $this->hasColumn('codepheno', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('pheno', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TApresence', array(
             'local' => 'codepheno',
             'foreign' => 'codepheno'));
    }
}