<?php

/**
 * BaseBibImportancesPopulation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_importance_population
 * @property string $nom_importance_population
 * @property string $desc_importance_population
 * @property Doctrine_Collection $BibTaxonsFaunePn
 * 
 * @method integer                  getIdImportancePopulation()     Returns the current record's "id_importance_population" value
 * @method string                   getNomImportancePopulation()    Returns the current record's "nom_importance_population" value
 * @method string                   getDescImportancePopulation()   Returns the current record's "desc_importance_population" value
 * @method Doctrine_Collection      getBibTaxonsFaunePn()           Returns the current record's "BibTaxonsFaunePn" collection
 * @method BibImportancesPopulation setIdImportancePopulation()     Sets the current record's "id_importance_population" value
 * @method BibImportancesPopulation setNomImportancePopulation()    Sets the current record's "nom_importance_population" value
 * @method BibImportancesPopulation setDescImportancePopulation()   Sets the current record's "desc_importance_population" value
 * @method BibImportancesPopulation setBibTaxonsFaunePn()           Sets the current record's "BibTaxonsFaunePn" collection
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibImportancesPopulation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.bib_importances_population');
        $this->hasColumn('id_importance_population', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom_importance_population', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('desc_importance_population', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BibTaxonsFaunePn', array(
             'local' => 'id_importance_population',
             'foreign' => 'id_importance_population'));
    }
}