<?php

/**
 * BaseBibOrdres
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ordre
 * @property integer $id_classe
 * @property string $nom_orde
 * @property BibClasses $BibClasses
 * @property Doctrine_Collection $BibFamilles
 * 
 * @method integer             getIdOrdre()     Returns the current record's "id_ordre" value
 * @method integer             getIdClasse()    Returns the current record's "id_classe" value
 * @method string              getNomOrde()     Returns the current record's "nom_orde" value
 * @method BibClasses          getBibClasses()  Returns the current record's "BibClasses" value
 * @method Doctrine_Collection getBibFamilles() Returns the current record's "BibFamilles" collection
 * @method BibOrdres           setIdOrdre()     Sets the current record's "id_ordre" value
 * @method BibOrdres           setIdClasse()    Sets the current record's "id_classe" value
 * @method BibOrdres           setNomOrde()     Sets the current record's "nom_orde" value
 * @method BibOrdres           setBibClasses()  Sets the current record's "BibClasses" value
 * @method BibOrdres           setBibFamilles() Sets the current record's "BibFamilles" collection
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibOrdres extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.bib_ordres');
        $this->hasColumn('id_ordre', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_classe', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nom_orde', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibClasses', array(
             'local' => 'id_classe',
             'foreign' => 'id_classe'));

        $this->hasMany('BibFamilles', array(
             'local' => 'id_ordre',
             'foreign' => 'id_ordre'));
    }
}