<?php

/**
 * BaseCorMessageTaxonCflore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_message_cflore
 * @property integer $id_taxon
 * @property BibTaxons $BibTaxons
 * @property BibMessagesCflore $BibMessagesCflore
 * 
 * @method integer               getIdMessageCflore()   Returns the current record's "id_message_cflore" value
 * @method integer               getIdTaxon()           Returns the current record's "id_taxon" value
 * @method BibTaxons             getBibTaxons()         Returns the current record's "BibTaxons" value
 * @method BibMessagesCflore     getBibMessagesCflore() Returns the current record's "BibMessagesCflore" value
 * @method CorMessageTaxonCflore setIdMessageCflore()   Sets the current record's "id_message_cflore" value
 * @method CorMessageTaxonCflore setIdTaxon()           Sets the current record's "id_taxon" value
 * @method CorMessageTaxonCflore setBibTaxons()         Sets the current record's "BibTaxons" value
 * @method CorMessageTaxonCflore setBibMessagesCflore() Sets the current record's "BibMessagesCflore" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorMessageTaxonCflore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactflore.cor_message_taxon_cflore');
        $this->hasColumn('id_message_cflore', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_taxon', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibTaxons', array(
             'local' => 'id_taxon',
             'foreign' => 'id_taxon'));

        $this->hasOne('BibMessagesCflore', array(
             'local' => 'id_message_cflore',
             'foreign' => 'id_message_cflore'));
    }
}