<?php

/**
 * BaseTZprospection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $indexzp
 * @property integer $cd_nom
 * @property integer $id_secteur_fp
 * @property integer $id_protocole
 * @property integer $id_lot
 * @property integer $id_organisme
 * @property date $dateobs
 * @property blob $the_geom
 * @property blob $the_geom_3857
 * @property blob $the_geom_local
 * @property blob $geom_mixte_3857
 * @property blob $geom_point_3857
 * @property timestamp $date_insert
 * @property timestamp $date_update
 * @property boolean $validation
 * @property boolean $topo_valid
 * @property boolean $erreur_signalee
 * @property boolean $supprime
 * @property string $saisie_initiale
 * @property string $taxon_saisi
 * @property string $insee
 * @property integer $srid_dessin
 * @property BibTaxonsFp $BibTaxonsFp
 * @property BibOrganismes $BibOrganismes
 * @property BibLots $BibLots
 * @property TProtocoles $TProtocoles
 * @property Doctrine_Collection $CorZpObs
 * @property Doctrine_Collection $TApresence
 * 
 * @method integer             get()                Returns the current record's "indexzp" value
 * @method integer             get()                Returns the current record's "cd_nom" value
 * @method integer             get()                Returns the current record's "id_secteur_fp" value
 * @method integer             get()                Returns the current record's "id_protocole" value
 * @method integer             get()                Returns the current record's "id_lot" value
 * @method integer             get()                Returns the current record's "id_organisme" value
 * @method date                get()                Returns the current record's "dateobs" value
 * @method blob                get()                Returns the current record's "the_geom" value
 * @method blob                get()                Returns the current record's "the_geom_3857" value
 * @method blob                get()                Returns the current record's "the_geom_local" value
 * @method blob                get()                Returns the current record's "geom_mixte_3857" value
 * @method blob                get()                Returns the current record's "geom_point_3857" value
 * @method timestamp           get()                Returns the current record's "date_insert" value
 * @method timestamp           get()                Returns the current record's "date_update" value
 * @method boolean             get()                Returns the current record's "validation" value
 * @method boolean             get()                Returns the current record's "topo_valid" value
 * @method boolean             get()                Returns the current record's "erreur_signalee" value
 * @method boolean             get()                Returns the current record's "supprime" value
 * @method string              get()                Returns the current record's "saisie_initiale" value
 * @method string              get()                Returns the current record's "taxon_saisi" value
 * @method string              get()                Returns the current record's "insee" value
 * @method integer             get()                Returns the current record's "srid_dessin" value
 * @method BibTaxonsFp         get()                Returns the current record's "BibTaxonsFp" value
 * @method BibOrganismes       get()                Returns the current record's "BibOrganismes" value
 * @method BibLots             get()                Returns the current record's "BibLots" value
 * @method TProtocoles         get()                Returns the current record's "TProtocoles" value
 * @method Doctrine_Collection get()                Returns the current record's "CorZpObs" collection
 * @method Doctrine_Collection get()                Returns the current record's "TApresence" collection
 * @method TZprospection       set()                Sets the current record's "indexzp" value
 * @method TZprospection       set()                Sets the current record's "cd_nom" value
 * @method TZprospection       set()                Sets the current record's "id_secteur_fp" value
 * @method TZprospection       set()                Sets the current record's "id_protocole" value
 * @method TZprospection       set()                Sets the current record's "id_lot" value
 * @method TZprospection       set()                Sets the current record's "id_organisme" value
 * @method TZprospection       set()                Sets the current record's "dateobs" value
 * @method TZprospection       set()                Sets the current record's "the_geom" value
 * @method TZprospection       set()                Sets the current record's "the_geom_3857" value
 * @method TZprospection       set()                Sets the current record's "the_geom_local" value
 * @method TZprospection       set()                Sets the current record's "geom_mixte_3857" value
 * @method TZprospection       set()                Sets the current record's "geom_point_3857" value
 * @method TZprospection       set()                Sets the current record's "date_insert" value
 * @method TZprospection       set()                Sets the current record's "date_update" value
 * @method TZprospection       set()                Sets the current record's "validation" value
 * @method TZprospection       set()                Sets the current record's "topo_valid" value
 * @method TZprospection       set()                Sets the current record's "erreur_signalee" value
 * @method TZprospection       set()                Sets the current record's "supprime" value
 * @method TZprospection       set()                Sets the current record's "saisie_initiale" value
 * @method TZprospection       set()                Sets the current record's "taxon_saisi" value
 * @method TZprospection       set()                Sets the current record's "insee" value
 * @method TZprospection       set()                Sets the current record's "srid_dessin" value
 * @method TZprospection       set()                Sets the current record's "BibTaxonsFp" value
 * @method TZprospection       set()                Sets the current record's "BibOrganismes" value
 * @method TZprospection       set()                Sets the current record's "BibLots" value
 * @method TZprospection       set()                Sets the current record's "TProtocoles" value
 * @method TZprospection       set()                Sets the current record's "CorZpObs" collection
 * @method TZprospection       set()                Sets the current record's "TApresence" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTZprospection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('florepatri.t_zprospection');
        $this->hasColumn('indexzp', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('cd_nom', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_secteur_fp', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('id_protocole', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('id_lot', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('id_organisme', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('dateobs', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('the_geom', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('the_geom_3857', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('the_geom_local', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('geom_mixte_3857', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('geom_point_3857', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('date_insert', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('date_update', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('validation', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('topo_valid', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('erreur_signalee', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('supprime', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('saisie_initiale', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('taxon_saisi', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('insee', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('srid_dessin', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibTaxonsFp', array(
             'local' => 'cd_nom',
             'foreign' => 'cd_nom'));

        $this->hasOne('BibOrganismes', array(
             'local' => 'id_organisme',
             'foreign' => 'id_organisme'));

        $this->hasOne('BibLots', array(
             'local' => 'id_lot',
             'foreign' => 'id_lot'));

        $this->hasOne('TProtocoles', array(
             'local' => 'id_protocole',
             'foreign' => 'id_protocole'));

        $this->hasMany('CorZpObs', array(
             'local' => 'indexzp',
             'foreign' => 'indexzp'));

        $this->hasMany('TApresence', array(
             'local' => 'indexzp',
             'foreign' => 'indexzp'));
    }
}