<?php

/**
 * BaseBibMessagesCflore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_message_cflore
 * @property string $texte_message_cflore
 * @property Doctrine_Collection $CorMessageTaxonCflore
 * 
 * @method integer             getIdMessageCflore()       Returns the current record's "id_message_cflore" value
 * @method string              getTexteMessageCflore()    Returns the current record's "texte_message_cflore" value
 * @method Doctrine_Collection getCorMessageTaxonCflore() Returns the current record's "CorMessageTaxonCflore" collection
 * @method BibMessagesCflore   setIdMessageCflore()       Sets the current record's "id_message_cflore" value
 * @method BibMessagesCflore   setTexteMessageCflore()    Sets the current record's "texte_message_cflore" value
 * @method BibMessagesCflore   setCorMessageTaxonCflore() Sets the current record's "CorMessageTaxonCflore" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibMessagesCflore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactflore.bib_messages_cflore');
        $this->hasColumn('id_message_cflore', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('texte_message_cflore', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CorMessageTaxonCflore', array(
             'local' => 'id_message_cflore',
             'foreign' => 'id_message_cflore'));
    }
}