<?php

/**
 * BaseBibProgrammes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_programme
 * @property string $nom_programme
 * @property string $desc_programme
 * @property boolean $actif
 * @property Doctrine_Collection $BibLots
 * 
 * @method integer             get()               Returns the current record's "id_programme" value
 * @method string              get()               Returns the current record's "nom_programme" value
 * @method string              get()               Returns the current record's "desc_programme" value
 * @method boolean             get()               Returns the current record's "actif" value
 * @method Doctrine_Collection get()               Returns the current record's "BibLots" collection
 * @method BibProgrammes       set()               Sets the current record's "id_programme" value
 * @method BibProgrammes       set()               Sets the current record's "nom_programme" value
 * @method BibProgrammes       set()               Sets the current record's "desc_programme" value
 * @method BibProgrammes       set()               Sets the current record's "actif" value
 * @method BibProgrammes       set()               Sets the current record's "BibLots" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibProgrammes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meta.bib_programmes');
        $this->hasColumn('id_programme', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom_programme', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('desc_programme', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('actif', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BibLots', array(
             'local' => 'id_programme',
             'foreign' => 'id_programme'));
    }
}