<?php

/**
 * BaseCorRoleDroitApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_role
 * @property integer $id_droit
 * @property integer $id_application
 * @property TRoles $TRoles
 * @property BibDroits $BibDroits
 * 
 * @method integer                 getIdRole()         Returns the current record's "id_role" value
 * @method integer                 getIdDroit()        Returns the current record's "id_droit" value
 * @method integer                 getIdApplication()  Returns the current record's "id_application" value
 * @method TRoles                  getTRoles()         Returns the current record's "TRoles" value
 * @method BibDroits               getBibDroits()      Returns the current record's "BibDroits" value
 * @method CorRoleDroitApplication setIdRole()         Sets the current record's "id_role" value
 * @method CorRoleDroitApplication setIdDroit()        Sets the current record's "id_droit" value
 * @method CorRoleDroitApplication setIdApplication()  Sets the current record's "id_application" value
 * @method CorRoleDroitApplication setTRoles()         Sets the current record's "TRoles" value
 * @method CorRoleDroitApplication setBibDroits()      Sets the current record's "BibDroits" value
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorRoleDroitApplication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utilisateurs.cor_role_droit_application');
        $this->hasColumn('id_role', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_droit', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_application', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TRoles', array(
             'local' => 'id_role',
             'foreign' => 'id_role'));

        $this->hasOne('BibDroits', array(
             'local' => 'id_droit',
             'foreign' => 'id_droit'));
    }
}