<?php

/**
 * BaseCorFsObservateur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_station
 * @property integer $id_role
 * @property TStationsFs $TStationsFs
 * @property TRoles $TRoles
 * 
 * @method integer          getIdStation()   Returns the current record's "id_station" value
 * @method integer          getIdRole()      Returns the current record's "id_role" value
 * @method TStationsFs      getTStationsFs() Returns the current record's "TStationsFs" value
 * @method TRoles           getTRoles()      Returns the current record's "TRoles" value
 * @method CorFsObservateur setIdStation()   Sets the current record's "id_station" value
 * @method CorFsObservateur setIdRole()      Sets the current record's "id_role" value
 * @method CorFsObservateur setTStationsFs() Sets the current record's "TStationsFs" value
 * @method CorFsObservateur setTRoles()      Sets the current record's "TRoles" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorFsObservateur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('florestation.cor_fs_observateur');
        $this->hasColumn('id_station', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_role', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TStationsFs', array(
             'local' => 'id_station',
             'foreign' => 'id_station'));

        $this->hasOne('TRoles', array(
             'local' => 'id_role',
             'foreign' => 'id_role'));
    }
}