<?php

/**
 * BaseCorTaxonAttribut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cd_ref
 * @property integer $id_attribut
 * @property string $valeur_attribut
 * @property BibAttributs $BibAttributs
 * @property BibNoms $BibNoms
 * 
 * @method integer          get()                Returns the current record's "cd_ref" value
 * @method integer          get()                Returns the current record's "id_attribut" value
 * @method string           get()                Returns the current record's "valeur_attribut" value
 * @method BibAttributs     get()                Returns the current record's "BibAttributs" value
 * @method BibNoms          get()                Returns the current record's "BibNoms" value
 * @method CorTaxonAttribut set()                Sets the current record's "cd_ref" value
 * @method CorTaxonAttribut set()                Sets the current record's "id_attribut" value
 * @method CorTaxonAttribut set()                Sets the current record's "valeur_attribut" value
 * @method CorTaxonAttribut set()                Sets the current record's "BibAttributs" value
 * @method CorTaxonAttribut set()                Sets the current record's "BibNoms" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorTaxonAttribut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.cor_taxon_attribut');
        $this->hasColumn('cd_ref', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_attribut', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('valeur_attribut', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibAttributs', array(
             'local' => 'id_attribut',
             'foreign' => 'id_attribut'));

        $this->hasOne('BibNoms', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));
    }
}