<?php

/**
 * BaseTRelevesInv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_releve_inv
 * @property integer $id_inv
 * @property integer $id_taxon
 * @property integer $id_critere_inv
 * @property integer $am
 * @property integer $af
 * @property integer $ai
 * @property integer $na
 * @property integer $cd_ref_origine
 * @property string $nom_taxon_saisi
 * @property string $commentaire
 * @property boolean $supprime
 * @property boolean $prelevement
 * @property BibCriteresInv $BibCriteresInv
 * @property BibTaxons $BibTaxons
 * @property TFichesInv $TFichesCf
 * @property Doctrine_Collection $VNomadeTaxonsInv
 * 
 * @method integer             getIdReleveInv()      Returns the current record's "id_releve_inv" value
 * @method integer             getIdInv()            Returns the current record's "id_inv" value
 * @method integer             getIdTaxon()          Returns the current record's "id_taxon" value
 * @method integer             getIdCritereInv()     Returns the current record's "id_critere_inv" value
 * @method integer             getAm()               Returns the current record's "am" value
 * @method integer             getAf()               Returns the current record's "af" value
 * @method integer             getAi()               Returns the current record's "ai" value
 * @method integer             getNa()               Returns the current record's "na" value
 * @method integer             getCdRefOrigine()     Returns the current record's "cd_ref_origine" value
 * @method string              getNomTaxonSaisi()    Returns the current record's "nom_taxon_saisi" value
 * @method string              getCommentaire()      Returns the current record's "commentaire" value
 * @method boolean             getSupprime()         Returns the current record's "supprime" value
 * @method boolean             getPrelevement()      Returns the current record's "prelevement" value
 * @method BibCriteresInv      getBibCriteresInv()   Returns the current record's "BibCriteresInv" value
 * @method BibTaxons           getBibTaxons()        Returns the current record's "BibTaxons" value
 * @method TFichesInv          getTFichesCf()        Returns the current record's "TFichesCf" value
 * @method Doctrine_Collection getVNomadeTaxonsInv() Returns the current record's "VNomadeTaxonsInv" collection
 * @method TRelevesInv         setIdReleveInv()      Sets the current record's "id_releve_inv" value
 * @method TRelevesInv         setIdInv()            Sets the current record's "id_inv" value
 * @method TRelevesInv         setIdTaxon()          Sets the current record's "id_taxon" value
 * @method TRelevesInv         setIdCritereInv()     Sets the current record's "id_critere_inv" value
 * @method TRelevesInv         setAm()               Sets the current record's "am" value
 * @method TRelevesInv         setAf()               Sets the current record's "af" value
 * @method TRelevesInv         setAi()               Sets the current record's "ai" value
 * @method TRelevesInv         setNa()               Sets the current record's "na" value
 * @method TRelevesInv         setCdRefOrigine()     Sets the current record's "cd_ref_origine" value
 * @method TRelevesInv         setNomTaxonSaisi()    Sets the current record's "nom_taxon_saisi" value
 * @method TRelevesInv         setCommentaire()      Sets the current record's "commentaire" value
 * @method TRelevesInv         setSupprime()         Sets the current record's "supprime" value
 * @method TRelevesInv         setPrelevement()      Sets the current record's "prelevement" value
 * @method TRelevesInv         setBibCriteresInv()   Sets the current record's "BibCriteresInv" value
 * @method TRelevesInv         setBibTaxons()        Sets the current record's "BibTaxons" value
 * @method TRelevesInv         setTFichesCf()        Sets the current record's "TFichesCf" value
 * @method TRelevesInv         setVNomadeTaxonsInv() Sets the current record's "VNomadeTaxonsInv" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTRelevesInv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactinv.t_releves_inv');
        $this->hasColumn('id_releve_inv', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('id_inv', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('id_taxon', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_critere_inv', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('am', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('af', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('ai', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('na', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cd_ref_origine', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nom_taxon_saisi', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('supprime', 'boolean', 1, array(
             'type' => 'boolean',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('prelevement', 'boolean', 1, array(
             'type' => 'boolean',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibCriteresInv', array(
             'local' => 'id_critere_inv',
             'foreign' => 'id_critere_inv'));

        $this->hasOne('BibTaxons', array(
             'local' => 'id_taxon',
             'foreign' => 'id_taxon'));

        $this->hasOne('TFichesInv as TFichesCf', array(
             'local' => 'id_inv',
             'foreign' => 'id_inv'));

        $this->hasMany('VNomadeTaxonsInv', array(
             'local' => 'id_taxon',
             'foreign' => 'id_taxon'));
    }
}