<?php

/**
 * BaseCorUniteSynthese
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_synthese
 * @property integer $id_unite_geo
 * @property Syntheseff $Syntheseff
 * @property LUnitesGeo $LUnitesGeo
 * 
 * @method integer          getIdSynthese()   Returns the current record's "id_synthese" value
 * @method integer          getIdUniteGeo()   Returns the current record's "id_unite_geo" value
 * @method Syntheseff       getSyntheseff()   Returns the current record's "Syntheseff" value
 * @method LUnitesGeo       getLUnitesGeo()   Returns the current record's "LUnitesGeo" value
 * @method CorUniteSynthese setIdSynthese()   Sets the current record's "id_synthese" value
 * @method CorUniteSynthese setIdUniteGeo()   Sets the current record's "id_unite_geo" value
 * @method CorUniteSynthese setSyntheseff()   Sets the current record's "Syntheseff" value
 * @method CorUniteSynthese setLUnitesGeo()   Sets the current record's "LUnitesGeo" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorUniteSynthese extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactinv.cor_unite_synthese');
        $this->hasColumn('id_synthese', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_unite_geo', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Syntheseff', array(
             'local' => 'id_synthese',
             'foreign' => 'id_synthese'));

        $this->hasOne('LUnitesGeo', array(
             'local' => 'id_unite_geo',
             'foreign' => 'id_unite_geo'));
    }
}