<?php

/**
 * BaseCorMessageTaxonCflore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_message_cflore
 * @property integer $id_nom
 * @property BibNoms $BibNoms
 * @property BibMessagesCflore $BibMessagesCflore
 * 
 * @method integer               get()                  Returns the current record's "id_message_cflore" value
 * @method integer               get()                  Returns the current record's "id_nom" value
 * @method BibNoms               get()                  Returns the current record's "BibNoms" value
 * @method BibMessagesCflore     get()                  Returns the current record's "BibMessagesCflore" value
 * @method CorMessageTaxonCflore set()                  Sets the current record's "id_message_cflore" value
 * @method CorMessageTaxonCflore set()                  Sets the current record's "id_nom" value
 * @method CorMessageTaxonCflore set()                  Sets the current record's "BibNoms" value
 * @method CorMessageTaxonCflore set()                  Sets the current record's "BibMessagesCflore" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorMessageTaxonCflore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactflore.cor_message_taxon_cflore');
        $this->hasColumn('id_message_cflore', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_nom', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibNoms', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));

        $this->hasOne('BibMessagesCflore', array(
             'local' => 'id_message_cflore',
             'foreign' => 'id_message_cflore'));
    }
}