<?php

/**
 * BaseBibFamilles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_famille
 * @property integer $id_ordre
 * @property string $nom_famille
 * @property BibOrdres $BibOrdres
 * @property Doctrine_Collection $BibTaxonsFaunePn
 * 
 * @method integer             getIdFamille()        Returns the current record's "id_famille" value
 * @method integer             getIdOrdre()          Returns the current record's "id_ordre" value
 * @method string              getNomFamille()       Returns the current record's "nom_famille" value
 * @method BibOrdres           getBibOrdres()        Returns the current record's "BibOrdres" value
 * @method Doctrine_Collection getBibTaxonsFaunePn() Returns the current record's "BibTaxonsFaunePn" collection
 * @method BibFamilles         setIdFamille()        Sets the current record's "id_famille" value
 * @method BibFamilles         setIdOrdre()          Sets the current record's "id_ordre" value
 * @method BibFamilles         setNomFamille()       Sets the current record's "nom_famille" value
 * @method BibFamilles         setBibOrdres()        Sets the current record's "BibOrdres" value
 * @method BibFamilles         setBibTaxonsFaunePn() Sets the current record's "BibTaxonsFaunePn" collection
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibFamilles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.bib_familles');
        $this->hasColumn('id_famille', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_ordre', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nom_famille', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibOrdres', array(
             'local' => 'id_ordre',
             'foreign' => 'id_ordre'));

        $this->hasMany('BibTaxonsFaunePn', array(
             'local' => 'id_famille',
             'foreign' => 'id_famille'));
    }
}