<?php

/**
 * BaseCorNomListe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_nom
 * @property integer $id_liste
 * @property BibListes $BibListes
 * @property BibNoms $BibNoms
 * 
 * @method integer     get()          Returns the current record's "id_nom" value
 * @method integer     get()          Returns the current record's "id_liste" value
 * @method BibListes   get()          Returns the current record's "BibListes" value
 * @method BibNoms     get()          Returns the current record's "BibNoms" value
 * @method CorNomListe set()          Sets the current record's "id_nom" value
 * @method CorNomListe set()          Sets the current record's "id_liste" value
 * @method CorNomListe set()          Sets the current record's "BibListes" value
 * @method CorNomListe set()          Sets the current record's "BibNoms" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorNomListe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.cor_nom_liste');
        $this->hasColumn('id_nom', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_liste', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibListes', array(
             'local' => 'id_liste',
             'foreign' => 'id_liste'));

        $this->hasOne('BibNoms', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));
    }
}