<?php

/**
 * BaseBibAbondancesBryo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_abondance
 * @property string $nom_abondance
 * @property Doctrine_Collection $CorBryoTaxon
 * 
 * @method string              getIdAbondance()   Returns the current record's "id_abondance" value
 * @method string              getNomAbondance()  Returns the current record's "nom_abondance" value
 * @method Doctrine_Collection getCorBryoTaxon()  Returns the current record's "CorBryoTaxon" collection
 * @method BibAbondancesBryo   setIdAbondance()   Sets the current record's "id_abondance" value
 * @method BibAbondancesBryo   setNomAbondance()  Sets the current record's "nom_abondance" value
 * @method BibAbondancesBryo   setCorBryoTaxon()  Sets the current record's "CorBryoTaxon" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibAbondancesBryo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bryophytes.bib_abondances');
        $this->hasColumn('id_abondance', 'string', 1, array(
             'type' => 'string',
             'primary' => true,
             'length' => 1,
             ));
        $this->hasColumn('nom_abondance', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CorBryoTaxon', array(
             'local' => 'id_abondance',
             'foreign' => 'id_abondance'));
    }
}