<?php

/**
 * BaseBibExpositions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id_exposition
 * @property string $nom_exposition
 * @property integer $tri_exposition
 * @property Doctrine_Collection $TStationsFs
 * 
 * @method string              getIdExposition()   Returns the current record's "id_exposition" value
 * @method string              getNomExposition()  Returns the current record's "nom_exposition" value
 * @method integer             getTriExposition()  Returns the current record's "tri_exposition" value
 * @method Doctrine_Collection getTStationsFs()    Returns the current record's "TStationsFs" collection
 * @method BibExpositions      setIdExposition()   Sets the current record's "id_exposition" value
 * @method BibExpositions      setNomExposition()  Sets the current record's "nom_exposition" value
 * @method BibExpositions      setTriExposition()  Sets the current record's "tri_exposition" value
 * @method BibExpositions      setTStationsFs()    Sets the current record's "TStationsFs" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibExpositions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('florestation.bib_expositions');
        $this->hasColumn('id_exposition', 'string', 2, array(
             'type' => 'string',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('nom_exposition', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('tri_exposition', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TStationsFs', array(
             'local' => 'id_exposition',
             'foreign' => 'id_exposition'));
    }
}