<?php

/**
 * BaseBibMessagesInv
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_message_inv
 * @property string $texte_message_inv
 * @property Doctrine_Collection $CorMessageTaxonInv
 * 
 * @method integer             getIdMessageInv()       Returns the current record's "id_message_inv" value
 * @method string              getTexteMessageInv()    Returns the current record's "texte_message_inv" value
 * @method Doctrine_Collection getCorMessageTaxonInv() Returns the current record's "CorMessageTaxonInv" collection
 * @method BibMessagesInv      setIdMessageInv()       Sets the current record's "id_message_inv" value
 * @method BibMessagesInv      setTexteMessageInv()    Sets the current record's "texte_message_inv" value
 * @method BibMessagesInv      setCorMessageTaxonInv() Sets the current record's "CorMessageTaxonInv" collection
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibMessagesInv extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactinv.bib_messages_inv');
        $this->hasColumn('id_message_inv', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('texte_message_inv', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CorMessageTaxonInv', array(
             'local' => 'id_message_inv',
             'foreign' => 'id_message_inv'));
    }
}