<?php

/**
 * BaseTaxref
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cd_nom
 * @property string $id_statut
 * @property integer $id_habitat
 * @property string $id_rang
 * @property string $regne
 * @property string $phylum
 * @property string $classe
 * @property string $ordre
 * @property string $famille
 * @property integer $cd_taxsup
 * @property integer $cd_ref
 * @property string $lb_nom
 * @property string $lb_auteur
 * @property string $nom_complet
 * @property string $nom_vern
 * @property string $nom_vern_eng
 * @property string $group1_inpn
 * @property string $group2_inpn
 * @property Doctrine_Collection $BibTaxonsFaunePn
 * @property Doctrine_Collection $Synthesefaune
 * 
 * @method integer             getCdNom()            Returns the current record's "cd_nom" value
 * @method string              getIdStatut()         Returns the current record's "id_statut" value
 * @method integer             getIdHabitat()        Returns the current record's "id_habitat" value
 * @method string              getIdRang()           Returns the current record's "id_rang" value
 * @method string              getRegne()            Returns the current record's "regne" value
 * @method string              getPhylum()           Returns the current record's "phylum" value
 * @method string              getClasse()           Returns the current record's "classe" value
 * @method string              getOrdre()            Returns the current record's "ordre" value
 * @method string              getFamille()          Returns the current record's "famille" value
 * @method integer             getCdTaxsup()         Returns the current record's "cd_taxsup" value
 * @method integer             getCdRef()            Returns the current record's "cd_ref" value
 * @method string              getLbNom()            Returns the current record's "lb_nom" value
 * @method string              getLbAuteur()         Returns the current record's "lb_auteur" value
 * @method string              getNomComplet()       Returns the current record's "nom_complet" value
 * @method string              getNomVern()          Returns the current record's "nom_vern" value
 * @method string              getNomVernEng()       Returns the current record's "nom_vern_eng" value
 * @method string              getGroup1Inpn()       Returns the current record's "group1_inpn" value
 * @method string              getGroup2Inpn()       Returns the current record's "group2_inpn" value
 * @method Doctrine_Collection getBibTaxonsFaunePn() Returns the current record's "BibTaxonsFaunePn" collection
 * @method Doctrine_Collection getSynthesefaune()    Returns the current record's "Synthesefaune" collection
 * @method Taxref              setCdNom()            Sets the current record's "cd_nom" value
 * @method Taxref              setIdStatut()         Sets the current record's "id_statut" value
 * @method Taxref              setIdHabitat()        Sets the current record's "id_habitat" value
 * @method Taxref              setIdRang()           Sets the current record's "id_rang" value
 * @method Taxref              setRegne()            Sets the current record's "regne" value
 * @method Taxref              setPhylum()           Sets the current record's "phylum" value
 * @method Taxref              setClasse()           Sets the current record's "classe" value
 * @method Taxref              setOrdre()            Sets the current record's "ordre" value
 * @method Taxref              setFamille()          Sets the current record's "famille" value
 * @method Taxref              setCdTaxsup()         Sets the current record's "cd_taxsup" value
 * @method Taxref              setCdRef()            Sets the current record's "cd_ref" value
 * @method Taxref              setLbNom()            Sets the current record's "lb_nom" value
 * @method Taxref              setLbAuteur()         Sets the current record's "lb_auteur" value
 * @method Taxref              setNomComplet()       Sets the current record's "nom_complet" value
 * @method Taxref              setNomVern()          Sets the current record's "nom_vern" value
 * @method Taxref              setNomVernEng()       Sets the current record's "nom_vern_eng" value
 * @method Taxref              setGroup1Inpn()       Sets the current record's "group1_inpn" value
 * @method Taxref              setGroup2Inpn()       Sets the current record's "group2_inpn" value
 * @method Taxref              setBibTaxonsFaunePn() Sets the current record's "BibTaxonsFaunePn" collection
 * @method Taxref              setSynthesefaune()    Sets the current record's "Synthesefaune" collection
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxref extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.taxref');
        $this->hasColumn('cd_nom', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_statut', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('id_habitat', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('id_rang', 'string', 4, array(
             'type' => 'string',
             'length' => 4,
             ));
        $this->hasColumn('regne', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('phylum', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('classe', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ordre', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('famille', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('cd_taxsup', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('cd_ref', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('lb_nom', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('lb_auteur', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('nom_complet', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom_vern', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nom_vern_eng', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('group1_inpn', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('group2_inpn', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BibTaxonsFaunePn', array(
             'local' => 'cd_nom',
             'foreign' => 'cd_nom'));

        $this->hasMany('Synthesefaune', array(
             'local' => 'cd_nom',
             'foreign' => 'cd_nom'));
    }
}