<?php

/**
 * BaseTRelevesCflore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_releve_cflore
 * @property integer $id_cflore
 * @property integer $id_nom
 * @property integer $id_abondance_cflore
 * @property integer $id_phenologie_cflore
 * @property boolean $validite_cflore
 * @property integer $cd_ref_origine
 * @property string $nom_taxon_saisi
 * @property string $commentaire
 * @property string $determinateur
 * @property boolean $supprime
 * @property boolean $herbier
 * @property BibAbondancesCflore $BibAbondancesCflore
 * @property BibPhenologiesCflore $BibPhenologiesCflore
 * @property BibNoms $BibNoms
 * @property TFichesCflore $TFichesCflore
 * @property Doctrine_Collection $VNomadeTaxonsFlore
 * 
 * @method integer              getIdReleveCflore()       Returns the current record's "id_releve_cflore" value
 * @method integer              getIdCflore()             Returns the current record's "id_cflore" value
 * @method integer              getIdNom()                Returns the current record's "id_nom" value
 * @method integer              getIdAbondanceCflore()    Returns the current record's "id_abondance_cflore" value
 * @method integer              getIdPhenologieCflore()   Returns the current record's "id_phenologie_cflore" value
 * @method boolean              getValiditeCflore()       Returns the current record's "validite_cflore" value
 * @method integer              getCdRefOrigine()         Returns the current record's "cd_ref_origine" value
 * @method string               getNomTaxonSaisi()        Returns the current record's "nom_taxon_saisi" value
 * @method string               getCommentaire()          Returns the current record's "commentaire" value
 * @method string               getDeterminateur()        Returns the current record's "determinateur" value
 * @method boolean              getSupprime()             Returns the current record's "supprime" value
 * @method boolean              getHerbier()              Returns the current record's "herbier" value
 * @method BibAbondancesCflore  getBibAbondancesCflore()  Returns the current record's "BibAbondancesCflore" value
 * @method BibPhenologiesCflore getBibPhenologiesCflore() Returns the current record's "BibPhenologiesCflore" value
 * @method BibNoms              getBibNoms()              Returns the current record's "BibNoms" value
 * @method TFichesCflore        getTFichesCflore()        Returns the current record's "TFichesCflore" value
 * @method Doctrine_Collection  getVNomadeTaxonsFlore()   Returns the current record's "VNomadeTaxonsFlore" collection
 * @method TRelevesCflore       setIdReleveCflore()       Sets the current record's "id_releve_cflore" value
 * @method TRelevesCflore       setIdCflore()             Sets the current record's "id_cflore" value
 * @method TRelevesCflore       setIdNom()                Sets the current record's "id_nom" value
 * @method TRelevesCflore       setIdAbondanceCflore()    Sets the current record's "id_abondance_cflore" value
 * @method TRelevesCflore       setIdPhenologieCflore()   Sets the current record's "id_phenologie_cflore" value
 * @method TRelevesCflore       setValiditeCflore()       Sets the current record's "validite_cflore" value
 * @method TRelevesCflore       setCdRefOrigine()         Sets the current record's "cd_ref_origine" value
 * @method TRelevesCflore       setNomTaxonSaisi()        Sets the current record's "nom_taxon_saisi" value
 * @method TRelevesCflore       setCommentaire()          Sets the current record's "commentaire" value
 * @method TRelevesCflore       setDeterminateur()        Sets the current record's "determinateur" value
 * @method TRelevesCflore       setSupprime()             Sets the current record's "supprime" value
 * @method TRelevesCflore       setHerbier()              Sets the current record's "herbier" value
 * @method TRelevesCflore       setBibAbondancesCflore()  Sets the current record's "BibAbondancesCflore" value
 * @method TRelevesCflore       setBibPhenologiesCflore() Sets the current record's "BibPhenologiesCflore" value
 * @method TRelevesCflore       setBibNoms()              Sets the current record's "BibNoms" value
 * @method TRelevesCflore       setTFichesCflore()        Sets the current record's "TFichesCflore" value
 * @method TRelevesCflore       setVNomadeTaxonsFlore()   Sets the current record's "VNomadeTaxonsFlore" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTRelevesCflore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactflore.t_releves_cflore');
        $this->hasColumn('id_releve_cflore', 'integer', 5, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('id_cflore', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('id_nom', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_abondance_cflore', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_phenologie_cflore', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('validite_cflore', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('cd_ref_origine', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('nom_taxon_saisi', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('determinateur', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('supprime', 'boolean', 1, array(
             'type' => 'boolean',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('herbier', 'boolean', 1, array(
             'type' => 'boolean',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibAbondancesCflore', array(
             'local' => 'id_abondance_cflore',
             'foreign' => 'id_abondance_cflore'));

        $this->hasOne('BibPhenologiesCflore', array(
             'local' => 'id_phenologie_cflore',
             'foreign' => 'id_phenologie_cflore'));

        $this->hasOne('BibNoms', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));

        $this->hasOne('TFichesCflore', array(
             'local' => 'id_cf',
             'foreign' => 'id_cf'));

        $this->hasMany('VNomadeTaxonsFlore', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));
    }
}