<?php

/**
 * BaseCorRoles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_role_groupe
 * @property integer $id_role_utilisateur
 * @property TRoles $TRolesGroupe
 * @property TRoles $TRolesUtilisateur
 * @property CorRoleMenu $CorRoleMenu
 * 
 * @method integer     get()                    Returns the current record's "id_role_groupe" value
 * @method integer     get()                    Returns the current record's "id_role_utilisateur" value
 * @method TRoles      get()                    Returns the current record's "TRolesGroupe" value
 * @method TRoles      get()                    Returns the current record's "TRolesUtilisateur" value
 * @method CorRoleMenu get()                    Returns the current record's "CorRoleMenu" value
 * @method CorRoles    set()                    Sets the current record's "id_role_groupe" value
 * @method CorRoles    set()                    Sets the current record's "id_role_utilisateur" value
 * @method CorRoles    set()                    Sets the current record's "TRolesGroupe" value
 * @method CorRoles    set()                    Sets the current record's "TRolesUtilisateur" value
 * @method CorRoles    set()                    Sets the current record's "CorRoleMenu" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorRoles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utilisateurs.cor_roles');
        $this->hasColumn('id_role_groupe', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_role_utilisateur', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TRoles as TRolesGroupe', array(
             'local' => 'id_role_groupe',
             'foreign' => 'id_role'));

        $this->hasOne('TRoles as TRolesUtilisateur', array(
             'local' => 'id_role_utilisateur',
             'foreign' => 'id_role'));

        $this->hasOne('CorRoleMenu', array(
             'local' => 'id_role_groupe',
             'foreign' => 'id_role'));
    }
}