<?php

/**
 * BaseBibListes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_liste
 * @property string $nom_liste
 * @property string $desc_liste
 * @property string $picto
 * @property Doctrine_Collection $CorCritereListe
 * @property Doctrine_Collection $CorNomListe
 * 
 * @method integer             get()                Returns the current record's "id_liste" value
 * @method string              get()                Returns the current record's "nom_liste" value
 * @method string              get()                Returns the current record's "desc_liste" value
 * @method string              get()                Returns the current record's "picto" value
 * @method Doctrine_Collection get()                Returns the current record's "CorCritereListe" collection
 * @method Doctrine_Collection get()                Returns the current record's "CorNomListe" collection
 * @method BibListes           set()                Sets the current record's "id_liste" value
 * @method BibListes           set()                Sets the current record's "nom_liste" value
 * @method BibListes           set()                Sets the current record's "desc_liste" value
 * @method BibListes           set()                Sets the current record's "picto" value
 * @method BibListes           set()                Sets the current record's "CorCritereListe" collection
 * @method BibListes           set()                Sets the current record's "CorNomListe" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBibListes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.bib_listes');
        $this->hasColumn('id_liste', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nom_liste', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('desc_liste', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('picto', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CorCritereListe', array(
             'local' => 'id_liste',
             'foreign' => 'id_liste'));

        $this->hasMany('CorNomListe', array(
             'local' => 'id_liste',
             'foreign' => 'id_liste'));
    }
}