<?php

/**
 * BaseCorRoleMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_role
 * @property integer $id_menu
 * @property TRoles $TRoles
 * @property Doctrine_Collection $CorRoles
 * 
 * @method integer             getIdRole()   Returns the current record's "id_role" value
 * @method integer             getIdMenu()   Returns the current record's "id_menu" value
 * @method TRoles              getTRoles()   Returns the current record's "TRoles" value
 * @method Doctrine_Collection getCorRoles() Returns the current record's "CorRoles" collection
 * @method CorRoleMenu         setIdRole()   Sets the current record's "id_role" value
 * @method CorRoleMenu         setIdMenu()   Sets the current record's "id_menu" value
 * @method CorRoleMenu         setTRoles()   Sets the current record's "TRoles" value
 * @method CorRoleMenu         setCorRoles() Sets the current record's "CorRoles" collection
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorRoleMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utilisateurs.cor_role_menu');
        $this->hasColumn('id_role', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_menu', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TRoles', array(
             'local' => 'id_role',
             'foreign' => 'id_role'));

        $this->hasMany('CorRoles', array(
             'local' => 'id_role',
             'foreign' => 'id_role_groupe'));
    }
}