<?php

/**
 * BaseCorUniteTaxonCflore
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_nom
 * @property integer $id_unite_geo
 * @property date $derniere_date
 * @property string $couleur
 * @property integer $nb_obs
 * @property BibNoms $BibNoms
 * @property LUnitesGeo $LUnitesGeo
 * @property Doctrine_Collection $VNomadeTaxonsFlore
 * 
 * @method integer             get()                   Returns the current record's "id_nom" value
 * @method integer             get()                   Returns the current record's "id_unite_geo" value
 * @method date                get()                   Returns the current record's "derniere_date" value
 * @method string              get()                   Returns the current record's "couleur" value
 * @method integer             get()                   Returns the current record's "nb_obs" value
 * @method BibNoms             get()                   Returns the current record's "BibNoms" value
 * @method LUnitesGeo          get()                   Returns the current record's "LUnitesGeo" value
 * @method Doctrine_Collection get()                   Returns the current record's "VNomadeTaxonsFlore" collection
 * @method CorUniteTaxonCflore set()                   Sets the current record's "id_nom" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "id_unite_geo" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "derniere_date" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "couleur" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "nb_obs" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "BibNoms" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "LUnitesGeo" value
 * @method CorUniteTaxonCflore set()                   Sets the current record's "VNomadeTaxonsFlore" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorUniteTaxonCflore extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactflore.cor_unite_taxon_cflore');
        $this->hasColumn('id_nom', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_unite_geo', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('derniere_date', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('couleur', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('nb_obs', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibNoms', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));

        $this->hasOne('LUnitesGeo', array(
             'local' => 'id_unite_geo',
             'foreign' => 'id_unite_geo'));

        $this->hasMany('VNomadeTaxonsFlore', array(
             'local' => 'id_nom',
             'foreign' => 'id_nom'));
    }
}