<?php

/**
 * BaseCorTaxonGroupe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_taxon
 * @property integer $id_groupe
 * @property BibGroupes $BibGroupes
 * @property BibTaxons $BibTaxons
 * 
 * @method integer        getIdTaxon()    Returns the current record's "id_taxon" value
 * @method integer        getIdGroupe()   Returns the current record's "id_groupe" value
 * @method BibGroupes     getBibGroupes() Returns the current record's "BibGroupes" value
 * @method BibTaxons      getBibTaxons()  Returns the current record's "BibTaxons" value
 * @method CorTaxonGroupe setIdTaxon()    Sets the current record's "id_taxon" value
 * @method CorTaxonGroupe setIdGroupe()   Sets the current record's "id_groupe" value
 * @method CorTaxonGroupe setBibGroupes() Sets the current record's "BibGroupes" value
 * @method CorTaxonGroupe setBibTaxons()  Sets the current record's "BibTaxons" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorTaxonGroupe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.cor_taxon_groupe');
        $this->hasColumn('id_taxon', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_groupe', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibGroupes', array(
             'local' => 'id_groupe',
             'foreign' => 'id_groupe'));

        $this->hasOne('BibTaxons', array(
             'local' => 'id_taxon',
             'foreign' => 'id_taxon'));
    }
}