<?php

/**
 * BaseSyntheseff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_synthese
 * @property integer $id_source
 * @property string $id_fiche_source
 * @property string $code_fiche_source
 * @property integer $id_organisme
 * @property integer $id_protocole
 * @property integer $id_precision
 * @property integer $cd_nom
 * @property integer $id_lot
 * @property integer $id_critere_synthese
 * @property string $insee
 * @property date $dateobs
 * @property string $observateurs
 * @property string $determinateur
 * @property string $remarques
 * @property integer $altitude_retenue
 * @property timestamp $date_insert
 * @property timestamp $date_update
 * @property string $derniere_action
 * @property boolean $supprime
 * @property integer $effectif_total
 * @property blob $the_geom_local
 * @property blob $the_geom_3857
 * @property blob $the_geom_point
 * @property LCommunes $LCommunes
 * @property TProtocoles $TProtocoles
 * @property BibOrganismes $BibOrganismes
 * @property BibSources $BibSources
 * @property TPrecisions $TPrecisions
 * @property Taxref $Taxref
 * @property BibLots $BibLots
 * @property BibCriteresSynthese $BibCriteresSynthese
 * @property Doctrine_Collection $CorUniteSynthese
 * @property Doctrine_Collection $CorZonesstatutSynthese
 * 
 * @method integer             get()                       Returns the current record's "id_synthese" value
 * @method integer             get()                       Returns the current record's "id_source" value
 * @method string              get()                       Returns the current record's "id_fiche_source" value
 * @method string              get()                       Returns the current record's "code_fiche_source" value
 * @method integer             get()                       Returns the current record's "id_organisme" value
 * @method integer             get()                       Returns the current record's "id_protocole" value
 * @method integer             get()                       Returns the current record's "id_precision" value
 * @method integer             get()                       Returns the current record's "cd_nom" value
 * @method integer             get()                       Returns the current record's "id_lot" value
 * @method integer             get()                       Returns the current record's "id_critere_synthese" value
 * @method string              get()                       Returns the current record's "insee" value
 * @method date                get()                       Returns the current record's "dateobs" value
 * @method string              get()                       Returns the current record's "observateurs" value
 * @method string              get()                       Returns the current record's "determinateur" value
 * @method string              get()                       Returns the current record's "remarques" value
 * @method integer             get()                       Returns the current record's "altitude_retenue" value
 * @method timestamp           get()                       Returns the current record's "date_insert" value
 * @method timestamp           get()                       Returns the current record's "date_update" value
 * @method string              get()                       Returns the current record's "derniere_action" value
 * @method boolean             get()                       Returns the current record's "supprime" value
 * @method integer             get()                       Returns the current record's "effectif_total" value
 * @method blob                get()                       Returns the current record's "the_geom_local" value
 * @method blob                get()                       Returns the current record's "the_geom_3857" value
 * @method blob                get()                       Returns the current record's "the_geom_point" value
 * @method LCommunes           get()                       Returns the current record's "LCommunes" value
 * @method TProtocoles         get()                       Returns the current record's "TProtocoles" value
 * @method BibOrganismes       get()                       Returns the current record's "BibOrganismes" value
 * @method BibSources          get()                       Returns the current record's "BibSources" value
 * @method TPrecisions         get()                       Returns the current record's "TPrecisions" value
 * @method Taxref              get()                       Returns the current record's "Taxref" value
 * @method BibLots             get()                       Returns the current record's "BibLots" value
 * @method BibCriteresSynthese get()                       Returns the current record's "BibCriteresSynthese" value
 * @method Doctrine_Collection get()                       Returns the current record's "CorUniteSynthese" collection
 * @method Doctrine_Collection get()                       Returns the current record's "CorZonesstatutSynthese" collection
 * @method Syntheseff          set()                       Sets the current record's "id_synthese" value
 * @method Syntheseff          set()                       Sets the current record's "id_source" value
 * @method Syntheseff          set()                       Sets the current record's "id_fiche_source" value
 * @method Syntheseff          set()                       Sets the current record's "code_fiche_source" value
 * @method Syntheseff          set()                       Sets the current record's "id_organisme" value
 * @method Syntheseff          set()                       Sets the current record's "id_protocole" value
 * @method Syntheseff          set()                       Sets the current record's "id_precision" value
 * @method Syntheseff          set()                       Sets the current record's "cd_nom" value
 * @method Syntheseff          set()                       Sets the current record's "id_lot" value
 * @method Syntheseff          set()                       Sets the current record's "id_critere_synthese" value
 * @method Syntheseff          set()                       Sets the current record's "insee" value
 * @method Syntheseff          set()                       Sets the current record's "dateobs" value
 * @method Syntheseff          set()                       Sets the current record's "observateurs" value
 * @method Syntheseff          set()                       Sets the current record's "determinateur" value
 * @method Syntheseff          set()                       Sets the current record's "remarques" value
 * @method Syntheseff          set()                       Sets the current record's "altitude_retenue" value
 * @method Syntheseff          set()                       Sets the current record's "date_insert" value
 * @method Syntheseff          set()                       Sets the current record's "date_update" value
 * @method Syntheseff          set()                       Sets the current record's "derniere_action" value
 * @method Syntheseff          set()                       Sets the current record's "supprime" value
 * @method Syntheseff          set()                       Sets the current record's "effectif_total" value
 * @method Syntheseff          set()                       Sets the current record's "the_geom_local" value
 * @method Syntheseff          set()                       Sets the current record's "the_geom_3857" value
 * @method Syntheseff          set()                       Sets the current record's "the_geom_point" value
 * @method Syntheseff          set()                       Sets the current record's "LCommunes" value
 * @method Syntheseff          set()                       Sets the current record's "TProtocoles" value
 * @method Syntheseff          set()                       Sets the current record's "BibOrganismes" value
 * @method Syntheseff          set()                       Sets the current record's "BibSources" value
 * @method Syntheseff          set()                       Sets the current record's "TPrecisions" value
 * @method Syntheseff          set()                       Sets the current record's "Taxref" value
 * @method Syntheseff          set()                       Sets the current record's "BibLots" value
 * @method Syntheseff          set()                       Sets the current record's "BibCriteresSynthese" value
 * @method Syntheseff          set()                       Sets the current record's "CorUniteSynthese" collection
 * @method Syntheseff          set()                       Sets the current record's "CorZonesstatutSynthese" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSyntheseff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('synthese.syntheseff');
        $this->hasColumn('id_synthese', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_source', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_fiche_source', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('code_fiche_source', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('id_organisme', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_protocole', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_precision', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cd_nom', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_lot', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('id_critere_synthese', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('insee', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('dateobs', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('observateurs', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('determinateur', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('remarques', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('altitude_retenue', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('date_insert', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('date_update', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('derniere_action', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('supprime', 'boolean', 1, array(
             'type' => 'boolean',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('effectif_total', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('the_geom_local', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('the_geom_3857', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('the_geom_point', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LCommunes', array(
             'local' => 'insee',
             'foreign' => 'insee'));

        $this->hasOne('TProtocoles', array(
             'local' => 'id_protocole',
             'foreign' => 'id_protocole'));

        $this->hasOne('BibOrganismes', array(
             'local' => 'id_organisme',
             'foreign' => 'id_organisme'));

        $this->hasOne('BibSources', array(
             'local' => 'id_source',
             'foreign' => 'id_source'));

        $this->hasOne('TPrecisions', array(
             'local' => 'id_precision',
             'foreign' => 'id_precision'));

        $this->hasOne('Taxref', array(
             'local' => 'cd_nom',
             'foreign' => 'cd_nom'));

        $this->hasOne('BibLots', array(
             'local' => 'id_lot',
             'foreign' => 'id_lot'));

        $this->hasOne('BibCriteresSynthese', array(
             'local' => 'id_critere_synthese',
             'foreign' => 'id_critere_synthese'));

        $this->hasMany('CorUniteSynthese', array(
             'local' => 'id_synthese',
             'foreign' => 'id_synthese'));

        $this->hasMany('CorZonesstatutSynthese', array(
             'local' => 'id_synthese',
             'foreign' => 'id_synthese'));
    }
}