<?php

/**
 * BaseTStationsBryo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_station
 * @property string $id_exposition
 * @property integer $id_protocole
 * @property integer $id_organisme
 * @property integer $id_lot
 * @property integer $id_support
 * @property date $dateobs
 * @property integer $surface
 * @property string $info_acces
 * @property string $complet_partiel
 * @property integer $altitude_saisie
 * @property integer $altitude_sig
 * @property integer $altitude_retenue
 * @property string $remarques
 * @property decimal $pdop
 * @property blob $the_geom_2154
 * @property blob $the_geom_3857
 * @property integer $srid_dessin
 * @property boolean $supprime
 * @property timestamp $date_insert
 * @property timestamp $date_update
 * @property string $insee
 * @property BibExpositionsBryo $BibExpositionsBryo
 * @property BibSupports $BibSupports
 * @property BibOrganismes $BibOrganismes
 * @property BibLots $BibLots
 * @property TProtocoles $TProtocoles
 * @property CorBryoTaxon $CorBryoTaxon
 * @property LCommunes $LCommunes
 * @property Doctrine_Collection $CorBryoObservateur
 * 
 * @method integer             getIdStation()          Returns the current record's "id_station" value
 * @method string              getIdExposition()       Returns the current record's "id_exposition" value
 * @method integer             getIdProtocole()        Returns the current record's "id_protocole" value
 * @method integer             getIdOrganisme()        Returns the current record's "id_organisme" value
 * @method integer             getIdLot()              Returns the current record's "id_lot" value
 * @method integer             getIdSupport()          Returns the current record's "id_support" value
 * @method date                getDateobs()            Returns the current record's "dateobs" value
 * @method integer             getSurface()            Returns the current record's "surface" value
 * @method string              getInfoAcces()          Returns the current record's "info_acces" value
 * @method string              getCompletPartiel()     Returns the current record's "complet_partiel" value
 * @method integer             getAltitudeSaisie()     Returns the current record's "altitude_saisie" value
 * @method integer             getAltitudeSig()        Returns the current record's "altitude_sig" value
 * @method integer             getAltitudeRetenue()    Returns the current record's "altitude_retenue" value
 * @method string              getRemarques()          Returns the current record's "remarques" value
 * @method decimal             getPdop()               Returns the current record's "pdop" value
 * @method blob                getTheGeom2154()        Returns the current record's "the_geom_2154" value
 * @method blob                getTheGeom3857()        Returns the current record's "the_geom_3857" value
 * @method integer             getSridDessin()         Returns the current record's "srid_dessin" value
 * @method boolean             getSupprime()           Returns the current record's "supprime" value
 * @method timestamp           getDateInsert()         Returns the current record's "date_insert" value
 * @method timestamp           getDateUpdate()         Returns the current record's "date_update" value
 * @method string              getInsee()              Returns the current record's "insee" value
 * @method BibExpositionsBryo  getBibExpositionsBryo() Returns the current record's "BibExpositionsBryo" value
 * @method BibSupports         getBibSupports()        Returns the current record's "BibSupports" value
 * @method BibOrganismes       getBibOrganismes()      Returns the current record's "BibOrganismes" value
 * @method BibLots             getBibLots()            Returns the current record's "BibLots" value
 * @method TProtocoles         getTProtocoles()        Returns the current record's "TProtocoles" value
 * @method CorBryoTaxon        getCorBryoTaxon()       Returns the current record's "CorBryoTaxon" value
 * @method LCommunes           getLCommunes()          Returns the current record's "LCommunes" value
 * @method Doctrine_Collection getCorBryoObservateur() Returns the current record's "CorBryoObservateur" collection
 * @method TStationsBryo       setIdStation()          Sets the current record's "id_station" value
 * @method TStationsBryo       setIdExposition()       Sets the current record's "id_exposition" value
 * @method TStationsBryo       setIdProtocole()        Sets the current record's "id_protocole" value
 * @method TStationsBryo       setIdOrganisme()        Sets the current record's "id_organisme" value
 * @method TStationsBryo       setIdLot()              Sets the current record's "id_lot" value
 * @method TStationsBryo       setIdSupport()          Sets the current record's "id_support" value
 * @method TStationsBryo       setDateobs()            Sets the current record's "dateobs" value
 * @method TStationsBryo       setSurface()            Sets the current record's "surface" value
 * @method TStationsBryo       setInfoAcces()          Sets the current record's "info_acces" value
 * @method TStationsBryo       setCompletPartiel()     Sets the current record's "complet_partiel" value
 * @method TStationsBryo       setAltitudeSaisie()     Sets the current record's "altitude_saisie" value
 * @method TStationsBryo       setAltitudeSig()        Sets the current record's "altitude_sig" value
 * @method TStationsBryo       setAltitudeRetenue()    Sets the current record's "altitude_retenue" value
 * @method TStationsBryo       setRemarques()          Sets the current record's "remarques" value
 * @method TStationsBryo       setPdop()               Sets the current record's "pdop" value
 * @method TStationsBryo       setTheGeom2154()        Sets the current record's "the_geom_2154" value
 * @method TStationsBryo       setTheGeom3857()        Sets the current record's "the_geom_3857" value
 * @method TStationsBryo       setSridDessin()         Sets the current record's "srid_dessin" value
 * @method TStationsBryo       setSupprime()           Sets the current record's "supprime" value
 * @method TStationsBryo       setDateInsert()         Sets the current record's "date_insert" value
 * @method TStationsBryo       setDateUpdate()         Sets the current record's "date_update" value
 * @method TStationsBryo       setInsee()              Sets the current record's "insee" value
 * @method TStationsBryo       setBibExpositionsBryo() Sets the current record's "BibExpositionsBryo" value
 * @method TStationsBryo       setBibSupports()        Sets the current record's "BibSupports" value
 * @method TStationsBryo       setBibOrganismes()      Sets the current record's "BibOrganismes" value
 * @method TStationsBryo       setBibLots()            Sets the current record's "BibLots" value
 * @method TStationsBryo       setTProtocoles()        Sets the current record's "TProtocoles" value
 * @method TStationsBryo       setCorBryoTaxon()       Sets the current record's "CorBryoTaxon" value
 * @method TStationsBryo       setLCommunes()          Sets the current record's "LCommunes" value
 * @method TStationsBryo       setCorBryoObservateur() Sets the current record's "CorBryoObservateur" collection
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTStationsBryo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bryophytes.t_stations_bryo');
        $this->hasColumn('id_station', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_exposition', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => 2,
             ));
        $this->hasColumn('id_protocole', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('id_organisme', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('id_lot', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('id_support', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 1,
             'length' => 4,
             ));
        $this->hasColumn('dateobs', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('surface', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('info_acces', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('complet_partiel', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('altitude_saisie', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('altitude_sig', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('altitude_retenue', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('remarques', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('pdop', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '2',
             ));
        $this->hasColumn('the_geom_2154', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('the_geom_3857', 'blob', null, array(
             'type' => 'blob',
             'length' => '',
             ));
        $this->hasColumn('srid_dessin', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('supprime', 'boolean', 1, array(
             'type' => 'boolean',
             'length' => 1,
             ));
        $this->hasColumn('date_insert', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('date_update', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('insee', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibExpositionsBryo', array(
             'local' => 'id_exposition',
             'foreign' => 'id_exposition'));

        $this->hasOne('BibSupports', array(
             'local' => 'id_support',
             'foreign' => 'id_support'));

        $this->hasOne('BibOrganismes', array(
             'local' => 'id_organisme',
             'foreign' => 'id_organisme'));

        $this->hasOne('BibLots', array(
             'local' => 'id_lot',
             'foreign' => 'id_lot'));

        $this->hasOne('TProtocoles', array(
             'local' => 'id_protocole',
             'foreign' => 'id_protocole'));

        $this->hasOne('CorBryoTaxon', array(
             'local' => 'id_station',
             'foreign' => 'id_station'));

        $this->hasOne('LCommunes', array(
             'local' => 'insee',
             'foreign' => 'insee'));

        $this->hasMany('CorBryoObservateur', array(
             'local' => 'id_station',
             'foreign' => 'id_station'));
    }
}