<?php

/**
 * BaseTaxrefProtectionArticles
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cd_protection
 * @property string $article
 * @property string $intitule
 * @property string $arrete
 * @property string $url_inpn
 * @property integer $cd_doc
 * @property string $url
 * @property integer $date_arrete
 * @property string $type_juridique
 * 
 * @method string                   getCdProtection()   Returns the current record's "cd_protection" value
 * @method string                   getArticle()        Returns the current record's "article" value
 * @method string                   getIntitule()       Returns the current record's "intitule" value
 * @method string                   getArrete()         Returns the current record's "arrete" value
 * @method string                   getUrlInpn()        Returns the current record's "url_inpn" value
 * @method integer                  getCdDoc()          Returns the current record's "cd_doc" value
 * @method string                   getUrl()            Returns the current record's "url" value
 * @method integer                  getDateArrete()     Returns the current record's "date_arrete" value
 * @method string                   getTypeJuridique()  Returns the current record's "type_juridique" value
 * @method TaxrefProtectionArticles setCdProtection()   Sets the current record's "cd_protection" value
 * @method TaxrefProtectionArticles setArticle()        Sets the current record's "article" value
 * @method TaxrefProtectionArticles setIntitule()       Sets the current record's "intitule" value
 * @method TaxrefProtectionArticles setArrete()         Sets the current record's "arrete" value
 * @method TaxrefProtectionArticles setUrlInpn()        Sets the current record's "url_inpn" value
 * @method TaxrefProtectionArticles setCdDoc()          Sets the current record's "cd_doc" value
 * @method TaxrefProtectionArticles setUrl()            Sets the current record's "url" value
 * @method TaxrefProtectionArticles setDateArrete()     Sets the current record's "date_arrete" value
 * @method TaxrefProtectionArticles setTypeJuridique()  Sets the current record's "type_juridique" value
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxrefProtectionArticles extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.taxref_protection_articles');
        $this->hasColumn('cd_protection', 'string', 20, array(
             'type' => 'string',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('article', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('intitule', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('arrete', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('url_inpn', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cd_doc', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_arrete', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('type_juridique', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}