<?php

/**
 * BaseCorTaxonListe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_taxon
 * @property integer $id_liste
 * @property BibListes $BibListes
 * @property BibTaxons $BibTaxons
 * 
 * @method integer       getIdTaxon()   Returns the current record's "id_taxon" value
 * @method integer       getIdListe()   Returns the current record's "id_liste" value
 * @method BibListes     getBibListes() Returns the current record's "BibListes" value
 * @method BibTaxons     getBibTaxons() Returns the current record's "BibTaxons" value
 * @method CorTaxonListe setIdTaxon()   Sets the current record's "id_taxon" value
 * @method CorTaxonListe setIdListe()   Sets the current record's "id_liste" value
 * @method CorTaxonListe setBibListes() Sets the current record's "BibListes" value
 * @method CorTaxonListe setBibTaxons() Sets the current record's "BibTaxons" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorTaxonListe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('taxonomie.cor_taxon_liste');
        $this->hasColumn('id_taxon', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_liste', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BibListes', array(
             'local' => 'id_liste',
             'foreign' => 'id_liste'));

        $this->hasOne('BibTaxons', array(
             'local' => 'id_taxon',
             'foreign' => 'id_taxon'));
    }
}