<?php

/**
 * BaseCorRoleFicheCf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_role
 * @property integer $id_cf
 * @property TRoles $TRoles
 * @property TFichesCf $TFichesCf
 * 
 * @method integer        getIdRole()    Returns the current record's "id_role" value
 * @method integer        getIdCf()      Returns the current record's "id_cf" value
 * @method TRoles         getTRoles()    Returns the current record's "TRoles" value
 * @method TFichesCf      getTFichesCf() Returns the current record's "TFichesCf" value
 * @method CorRoleFicheCf setIdRole()    Sets the current record's "id_role" value
 * @method CorRoleFicheCf setIdCf()      Sets the current record's "id_cf" value
 * @method CorRoleFicheCf setTRoles()    Sets the current record's "TRoles" value
 * @method CorRoleFicheCf setTFichesCf() Sets the current record's "TFichesCf" value
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCorRoleFicheCf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactfaune.cor_role_fiche_cf');
        $this->hasColumn('id_role', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_cf', 'integer', 5, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TRoles', array(
             'local' => 'id_role',
             'foreign' => 'id_role'));

        $this->hasOne('TFichesCf', array(
             'local' => 'id_cf',
             'foreign' => 'id_cf'));
    }
}