<?php

/**
 * BaseSpatialRefSys
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $srid
 * @property string $auth_name
 * @property integer $auth_srid
 * @property string $srtext
 * @property string $proj4text
 * 
 * @method integer       getSrid()      Returns the current record's "srid" value
 * @method string        getAuthName()  Returns the current record's "auth_name" value
 * @method integer       getAuthSrid()  Returns the current record's "auth_srid" value
 * @method string        getSrtext()    Returns the current record's "srtext" value
 * @method string        getProj4text() Returns the current record's "proj4text" value
 * @method SpatialRefSys setSrid()      Sets the current record's "srid" value
 * @method SpatialRefSys setAuthName()  Sets the current record's "auth_name" value
 * @method SpatialRefSys setAuthSrid()  Sets the current record's "auth_srid" value
 * @method SpatialRefSys setSrtext()    Sets the current record's "srtext" value
 * @method SpatialRefSys setProj4text() Sets the current record's "proj4text" value
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpatialRefSys extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spatial_ref_sys');
        $this->hasColumn('srid', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('auth_name', 'string', 256, array(
             'type' => 'string',
             'length' => 256,
             ));
        $this->hasColumn('auth_srid', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('srtext', 'string', 2048, array(
             'type' => 'string',
             'length' => 2048,
             ));
        $this->hasColumn('proj4text', 'string', 2048, array(
             'type' => 'string',
             'length' => 2048,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}