// WARNING: this file was auto generated by GeoNature command line.
// See Jinja template with ".sample" file extension in same directory.

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeContentComponent } from '../components/home-content/home-content.component';
import { PageNotFoundComponent } from '../components/page-not-found/page-not-found.component';
import { AuthGuard, ModuleGuardService } from '@geonature/routing/routes-guards.service';

import { SignUpGuard } from '@geonature/modules/login/routes-guard.service';
import { SignUpComponent } from '../modules/login/sign-up/sign-up.component';

import { UserManagementGuard } from '@geonature/modules/login/routes-guard.service';
import { NewPasswordComponent } from '../modules/login/new-password/new-password.component';

import { LoginComponent } from '../modules/login/login/login.component';
import { NavHomeComponent } from '../components/nav-home/nav-home.component';
import { MediasTestComponent } from '@geonature_common/form/media/medias-test.component';

const defaultRoutes: Routes = [
  {
    path: 'login',
    component: LoginComponent,
  },

  {
    path: 'inscription',
    component: SignUpComponent,
    canActivate: [SignUpGuard],
  },

  {
    path: 'new-password',
    component: NewPasswordComponent,
    canActivate: [UserManagementGuard],
  },

  {
    path: '',
    component: NavHomeComponent,
    canActivateChild: [AuthGuard],
    children: [
      {
        path: '',
        component: HomeContentComponent,
      },
      {
        path: 'synthese',
        data: { module_code: 'synthese' },
        canActivate: [ModuleGuardService],
        loadChildren: () =>
          import('@geonature/syntheseModule/synthese.module').then((m) => m.SyntheseModule),
      },
      {
        path: 'metadata',
        data: { module_code: 'metadata' },
        canActivate: [ModuleGuardService],
        loadChildren: () =>
          import('@geonature/metadataModule/metadata.module').then((m) => m.MetadataModule),
      },
      {
        path: 'admin',
        data: { module_code: 'admin' },
        loadChildren: () =>
          import('@geonature/adminModule/admin.module').then((m) => m.AdminModule),
        canActivate: [ModuleGuardService],
      },

      {
        path: 'user',
        data: { module_code: 'user' },
        loadChildren: () => import('@geonature/userModule/user.module').then((m) => m.UserModule),
      },
      {
        path: '**',
        component: PageNotFoundComponent,
      },
    ],
  },
];

export const routing = RouterModule.forRoot(defaultRoutes, { useHash: true });
