"""
Default columns for the export in synthese
"""

DEFAULT_EXPORT_COLUMNS = [
    "id_synthese",
    "id_origine",
    "uuid_perm_sinp",
    "date_debut",
    "date_fin",
    "heure_debut",
    "heure_fin",
    "cd_nom",
    "cd_ref",
    "nom_valide",
    "nom_cite",
    "regne",
    "group1_inpn",
    "group2_inpn",
    "classe",
    "ordre",
    "famille",
    "rang_taxo",
    "nombre_min",
    "nombre_max",
    "altitude_min",
    "altitude_max",
    "profondeur_min",
    "profondeur_max",
    "observateurs",
    "determinateur",
    "comment_releve",
    "comment_occurrence",
    "validateur",
    "niveau_validation",
    "date_validation",
    "comment_validation",
    "date_creation",
    "date_modification",
    "preuve_numerique_url",
    "preuve_non_numerique",
    "jdd_nom",
    "jdd_uuid",
    "jdd_id",
    "ca_nom",
    "ca_uuid",
    "ca_id",
    "cd_habref",
    "cd_habitat",
    "nom_habitat",
    "precision_geographique",
    "communes",
    "geometrie_wkt_4326",
    "x_centroid_4326",
    "y_centroid_4326",
    "nom_lieu",
    "nature_objet_geo",
    "type_regroupement",
    "methode_regroupement",
    "uuid_perm_grp_sinp",
    "technique_observation",
    "biologique_statut",
    "etat_biologique",
    "biogeographique_statut",
    "naturalite",
    "preuve_existante",
    "niveau_precision_diffusion",
    "stade_vie",
    "sexe",
    "objet_denombrement",
    "type_denombrement",
    "niveau_sensibilite",
    "statut_observation,
    "floutage_dee",
    "statut_source",
    "type_info_geo",
    "methode_determination",
    "comportement",
    "reference_biblio",
]


#
DEFAULT_COLUMNS_API_SYNTHESE = [
    "id_synthese",
    "date_min",
    "observers",
    "nom_valide",
    "dataset_name",
]

# Colonnes renvoyer par l'API synthese qui sont obligatoires pour que les fonctionnalites
#  front fonctionnent
MANDATORY_COLUMNS = ["entity_source_pk_value", "url_source", "cd_nom"]

# CONFIG MAP-LIST
DEFAULT_LIST_COLUMN = [
    {"prop": "nom_vern_or_lb_nom", "name": "Taxon", "max_width": 200},
    {"prop": "date_min", "name": "Date obs", "max_width": 100},
    {"prop": "dataset_name", "name": "JDD", "max_width": 200},
    {"prop": "observers", "name": "observateur", "max_width": 200},
]
