server {
    listen       ${NGINX_PORT};
    server_name  ${NGINX_HOST};

    location ${GEONATURE_FRONTEND_PREFIX} {
        alias  /usr/share/nginx/html/;
        index  index.html index.htm;
    }
}
