"""Update fields and themes

Revision ID: 699c25251384
Revises: 681062ef2939
Create Date: 2022-05-10 20:18:37.214323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "699c25251384"
down_revision = "681062ef2939"
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table(
        old_table_name="dict_fields",
        new_table_name="bib_fields",
        schema="gn_imports",
    )
    op.rename_table(
        old_table_name="dict_themes",
        new_table_name="bib_themes",
        schema="gn_imports",
    )
    op.rename_table(
        old_table_name="dict_errors",
        new_table_name="bib_errors_types",
        schema="gn_imports",
    )

    op.execute(
        """
    DELETE FROM
        gn_imports.bib_fields
    WHERE
        name_field = 'id_nomenclature_info_geo_type'
    """
    )
    op.execute(
        """
    UPDATE
        gn_imports.t_fieldmappings
    SET
        values = values::jsonb - 'id_nomenclature_info_geo_type'
    """
    )
    op.execute(
        """
    UPDATE
        gn_imports.t_contentmappings
    SET
        values = values::jsonb - 'TYP_INF_GEO'
    """
    )

    op.execute(
        """
    UPDATE
        gn_imports.bib_fields
    SET
        fr_label = 'Générer les identifiants SINP manquants'
    WHERE
        name_field = 'unique_id_sinp_generate'
    """
    )
    op.execute(
        """
    UPDATE
        gn_imports.bib_fields
    SET
        fr_label = 'Générer les altitudes manquantes'
    WHERE
        name_field = 'altitudes_generate'
    """
    )


def downgrade():
    op.execute(
        """
    UPDATE
        gn_imports.bib_fields
    SET
        fr_label = E'Générer l\\'identifiant SINP'
    WHERE
        name_field = 'unique_id_sinp_generate'
    """
    )
    op.execute(
        """
    UPDATE
        gn_imports.bib_fields
    SET
        fr_label = 'Générer les altitudes'
    WHERE
        name_field = 'altitudes_generate'
    """
    )

    op.execute(
        """
    INSERT INTO
        gn_imports.bib_fields
    (
        name_field,
        fr_label,
        type_field,
        mandatory,
        autogenerated,
        id_theme,
        order_field,
        display,
        comment,
        mnemonique,
        source_field,
        synthese_field
    )
    VALUES
    (
        'id_nomenclature_info_geo_type',
        E'Type d\\'information géographique',
        'integer',
        FALSE,
        FALSE,
        (SELECT id_theme FROM gn_imports.bib_themes WHERE name_theme = 'statement_info'),
        13,
        TRUE,
        'Correspondance champs standard: typeInfoGeo',
        'TYP_INF_GEO',
        'src_id_nomenclature_info_geo_type',
        'id_nomenclature_info_geo_type'
    )
    """
    )

    op.rename_table(
        new_table_name="dict_fields",
        old_table_name="bib_fields",
        schema="gn_imports",
    )
    op.rename_table(
        new_table_name="dict_themes",
        old_table_name="bib_themes",
        schema="gn_imports",
    )
    op.rename_table(
        new_table_name="dict_errors",
        old_table_name="bib_errors_types",
        schema="gn_imports",
    )
