services:
  postgres:
    image: postgis/postgis:13-3.2
    environment:
      - POSTGRES_DB=geonature2db
      - POSTGRES_USER=geonatadmin
      - POSTGRES_PASSWORD=geonatpasswd
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data

  api:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
      target: prod
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config/:/dist/config/
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - GEONATURE_CONFIG_FILE=${GEONATURE_CONFIG_FILE:-/dist/config/docker_config.toml}
    ports:
      - "${GEONATURE_BACKEND_PORT:-8000}:8000"

  web:
    build: ./frontend
    ports:
      - "${GEONATURE_FRONTEND_PORT:-4200}:80"


volumes:
  postgres:
  redis:
