<?php

/**
 * Syntheseff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    faune
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Syntheseff extends BaseSyntheseff
{
}
