<?php

/**
 * TApresence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    geonature
 * @subpackage model
 * @author     Gil Deluermoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TApresence extends BaseTApresence
{
    /**
	 * Update current object geometry
	 *
	 * @param unknown_type $geometry
	 */
	public function updateGeometry($geometry)
	{

    Doctrine_Query::create()->update('TApresence')
      ->set('the_geom_local','multi(geometryFromText(?, '.sfGeonatureConfig::$srid_local.'))', $geometry)
      ->where('indexap=?', $this->getIndexap())
      ->execute();
	}
}
