URL_APPLICATION = 'http://localhost:4200'
API_ENDPOINT = 'http://localhost:8000'
API_TAXHUB = 'http://localhost:5000/api'

# Overrided by Jenkins with environment variables
SQLALCHEMY_DATABASE_URI = 'postgresql://user:password@localhost:5432/dbname'
SECRET_KEY = '4477169cd4369d5ab3d769bf303ab0f7'
