Cypress.Commands.add('backToImportList', () => {
  // Ignore an exception generated by bokeh not being able to find 'chatreport'
  cy.on('uncaught:exception', (err, runnable) => {
    return false;
  });
  cy.get('[data-qa="import-report-back"]').click();
});
