"""Add etat_conservation, date_determ, url_preuve_numerique, commentaire to habitats

Revision ID: f45176d77944
Revises: fc6f7f3cb801
Create Date: 2026-09-22 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Table, MetaData
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
revision = "f45176d77944"
down_revision = "fc6f7f3cb801"
branch_labels = None
depends_on = ("b19f75d0e9a3",)


def upgrade():
    conn = op.get_bind()
    metadata = MetaData()
    session = Session(bind=conn)

    op.add_column(
        "t_habitats",
        sa.Column(
            "id_nomenclature_etat_conservation",
            sa.Integer(),
            sa.ForeignKey("ref_nomenclatures.t_nomenclatures.id_nomenclature"),
            nullable=True,
        ),
        schema="pr_occhab",
    )
    op.add_column(
        "t_habitats",
        sa.Column("date_determ", sa.Date(), nullable=True),
        schema="pr_occhab",
    )
    op.add_column(
        "t_habitats",
        sa.Column("url_preuve_numerique", sa.Unicode(), nullable=True),
        schema="pr_occhab",
    )
    op.add_column(
        "t_habitats",
        sa.Column("commentaire", sa.Unicode(), nullable=True),
        schema="pr_occhab",
    )

    op.add_column(
        "t_imports_occhab",
        sa.Column("src_id_nomenclature_etat_conservation", sa.String, nullable=True),
        schema="gn_imports",
    )
    op.add_column(
        "t_imports_occhab",
        sa.Column(
            "id_nomenclature_etat_conservation",
            sa.Integer(),
            sa.ForeignKey("ref_nomenclatures.t_nomenclatures.id_nomenclature"),
            nullable=True,
        ),
        schema="gn_imports",
    )
    op.add_column(
        "t_imports_occhab",
        sa.Column("src_date_determ", sa.String, nullable=True),
        schema="gn_imports",
    )
    op.add_column(
        "t_imports_occhab",
        sa.Column("date_determ", sa.Date(), nullable=True),
        schema="gn_imports",
    )
    op.add_column(
        "t_imports_occhab",
        sa.Column("url_preuve_numerique", sa.String, nullable=True),
        schema="gn_imports",
    )
    op.add_column(
        "t_imports_occhab",
        sa.Column("commentaire", sa.String, nullable=True),
        schema="gn_imports",
    )

    destination = sa.Table("bib_destinations", metadata, schema="gn_imports", autoload_with=conn)
    entity = sa.Table("bib_entities", metadata, schema="gn_imports", autoload_with=conn)
    theme = sa.Table("bib_themes", metadata, schema="gn_imports", autoload_with=conn)
    field = sa.Table("bib_fields", metadata, schema="gn_imports", autoload_with=conn)
    cor_entity_field = sa.Table(
        "cor_entity_field", metadata, schema="gn_imports", autoload_with=conn
    )

    id_dest_occhab = session.scalar(
        sa.select(destination.c.id_destination).where(destination.c.code == "occhab")
    )
    id_entity_habitat = session.scalar(
        sa.select(entity.c.id_entity).where(entity.c.code == "habitat")
    )
    id_theme_general = session.scalar(
        sa.select(theme.c.id_theme).where(theme.c.name_theme == "general_info")
    )

    new_fields = [
        (
            dict(
                id_destination=id_dest_occhab,
                name_field="id_nomenclature_etat_conservation",
                fr_label="Etat de conservation",
                mandatory=False,
                autogenerated=False,
                display=True,
                mnemonique="ETAT_CONSERVATION_HAB",
                source_field="src_id_nomenclature_etat_conservation",
                dest_field="id_nomenclature_etat_conservation",
                type_field="nomenclature",
            ),
            "Correspondance champs standard: etatConservation",
        ),
        (
            dict(
                id_destination=id_dest_occhab,
                name_field="date_determ",
                fr_label="Date de détermination",
                mandatory=False,
                autogenerated=False,
                display=True,
                mnemonique=None,
                source_field="src_date_determ",
                dest_field="date_determ",
                type_field="date",
            ),
            "Correspondance champs standard: dateDeterm",
        ),
        (
            dict(
                id_destination=id_dest_occhab,
                name_field="url_preuve_numerique",
                fr_label="URL de la preuve numérique",
                mandatory=False,
                autogenerated=False,
                display=True,
                mnemonique=None,
                source_field="url_preuve_numerique",
                dest_field="url_preuve_numerique",
                type_field="textarea",
            ),
            "Correspondance champs standard: urlPreuveNumerique",
        ),
        (
            dict(
                id_destination=id_dest_occhab,
                name_field="commentaire",
                fr_label="Commentaire",
                mandatory=False,
                autogenerated=False,
                display=True,
                mnemonique=None,
                source_field="commentaire",
                dest_field="commentaire",
                type_field="textarea",
            ),
            "Correspondance champs standard: commentaire",
        ),
    ]

    max_order = (
        session.scalar(
            sa.select(sa.func.max(cor_entity_field.c.order_field)).where(
                cor_entity_field.c.id_entity == id_entity_habitat
            )
        )
        or 0
    )

    for i, (values, comment) in enumerate(new_fields, start=1):
        id_field = session.execute(
            sa.insert(field).values(**values).returning(field.c.id_field)
        ).scalar()
        session.execute(
            sa.insert(cor_entity_field).values(
                id_entity=id_entity_habitat,
                id_field=id_field,
                id_theme=id_theme_general,
                order_field=max_order + i,
                comment=comment,
            )
        )
    session.commit()


def downgrade():
    conn = op.get_bind()
    metadata = MetaData()
    session = Session(bind=conn)

    field = sa.Table("bib_fields", metadata, schema="gn_imports", autoload_with=conn)
    cor_entity_field = sa.Table(
        "cor_entity_field", metadata, schema="gn_imports", autoload_with=conn
    )

    for name_field in (
        "id_nomenclature_etat_conservation",
        "date_determ",
        "url_preuve_numerique",
        "commentaire",
    ):
        id_field = session.scalar(
            sa.select(field.c.id_field).where(field.c.name_field == name_field)
        )
        if id_field is not None:
            session.execute(
                sa.delete(cor_entity_field).where(cor_entity_field.c.id_field == id_field)
            )
            session.execute(sa.delete(field).where(field.c.id_field == id_field))
    session.commit()

    op.drop_column("t_imports_occhab", "commentaire", schema="gn_imports")
    op.drop_column("t_imports_occhab", "url_preuve_numerique", schema="gn_imports")
    op.drop_column("t_imports_occhab", "date_determ", schema="gn_imports")
    op.drop_column("t_imports_occhab", "src_date_determ", schema="gn_imports")
    op.drop_column("t_imports_occhab", "id_nomenclature_etat_conservation", schema="gn_imports")
    op.drop_column("t_imports_occhab", "src_id_nomenclature_etat_conservation", schema="gn_imports")

    op.drop_column("t_habitats", "commentaire", schema="pr_occhab")
    op.drop_column("t_habitats", "url_preuve_numerique", schema="pr_occhab")
    op.drop_column("t_habitats", "date_determ", schema="pr_occhab")
    op.drop_column("t_habitats", "id_nomenclature_etat_conservation", schema="pr_occhab")
