"""
Static shell completion for the 'geonature' command.

Click dynamic completion runs the whole 'geonature' command (and thus creates the
Flask app) on each <Tab>, which takes several seconds. Here we walk the command
tree once and write a bash/zsh script containing the list of commands and options.
"""

import subprocess
import sys
from pathlib import Path

import click

from geonature.core.command.main import main

COMPLETION_FILE_NAME = "geonature_completion"


def default_completion_file():
    """Completion file sourced by the virtualenv 'activate' script (see install/01_install_backend.sh)."""
    return Path(sys.prefix) / "bin" / COMPLETION_FILE_NAME


def iter_command_tree(command, ctx, path=()):
    """
    Yield (path, subcommands, options, value_options) for the given command and its children.
    """
    subcommands = []
    if isinstance(command, click.Group):
        for name in command.list_commands(ctx):
            subcommand = command.get_command(ctx, name)
            if subcommand is None or subcommand.hidden:
                continue
            subcommands.append((name, subcommand))

    options, value_options = [], []
    params = list(command.params)
    help_option = command.get_help_option(ctx)
    if help_option is not None:
        params.append(help_option)
    for param in params:
        if not isinstance(param, click.Option) or param.hidden:
            continue
        opts = param.opts + param.secondary_opts
        options += opts
        if not param.is_flag and not param.count:
            value_options += param.opts

    yield path, [name for name, _ in subcommands], options, value_options

    for name, subcommand in subcommands:
        sub_ctx = click.Context(subcommand, info_name=name, parent=ctx)
        yield from iter_command_tree(subcommand, sub_ctx, path + (name,))


SCRIPT_TEMPLATE = """\
# GeoNature command static completion (bash & zsh)
# Generated by 'geonature generate-completion', do not edit.
# Regenerate it after installing or upgrading GeoNature or a module.

_geonature_spec() {{
    case "$1" in
{cases}
        *) _gn_cmds=""; _gn_opts=""; _gn_vopts="" ;;
    esac
}}

if [ -n "${{ZSH_VERSION:-}}" ]; then
    _geonature() {{
        local cmd_path="" word i prev _gn_cmds _gn_opts _gn_vopts
        for ((i = 2; i < CURRENT; i++)); do
            word="${{words[i]}}"
            _geonature_spec "$cmd_path"
            # unknown words (arguments, option values) are skipped; '_' is accepted for '-'
            case " $_gn_cmds " in
                *" $word "*) cmd_path="${{cmd_path:+$cmd_path }}$word" ;;
                *" ${{word//_/-}} "*) cmd_path="${{cmd_path:+$cmd_path }}${{word//_/-}}" ;;
            esac
        done
        _geonature_spec "$cmd_path"
        prev="${{words[CURRENT-1]}}"
        if [[ " $_gn_vopts " == *" $prev "* ]]; then
            _files
        elif [[ "$PREFIX" == -* ]]; then
            compadd -- ${{=_gn_opts}}
        elif [[ -n "$_gn_cmds" ]]; then
            compadd -- ${{=_gn_cmds}}
        else
            _files
        fi
    }}
    if (( $+functions[compdef] )); then
        compdef _geonature geonature
    fi
elif [ -n "${{BASH_VERSION:-}}" ]; then
    _geonature() {{
        local cur prev cmd_path="" word i _gn_cmds _gn_opts _gn_vopts
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
        for ((i = 1; i < COMP_CWORD; i++)); do
            word="${{COMP_WORDS[i]}}"
            _geonature_spec "$cmd_path"
            # unknown words (arguments, option values) are skipped; '_' is accepted for '-'
            case " $_gn_cmds " in
                *" $word "*) cmd_path="${{cmd_path:+$cmd_path }}$word" ;;
                *" ${{word//_/-}} "*) cmd_path="${{cmd_path:+$cmd_path }}${{word//_/-}}" ;;
            esac
        done
        _geonature_spec "$cmd_path"
        COMPREPLY=()
        if [[ " $_gn_vopts " == *" $prev "* ]]; then
            return  # complete -o default: fall back to file names
        elif [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$_gn_opts" -- "$cur"))
        elif [[ -n "$_gn_cmds" ]]; then
            COMPREPLY=($(compgen -W "$_gn_cmds" -- "$cur"))
        fi
    }}
    complete -o default -F _geonature geonature
fi
"""


def generate_completion_script(ctx):
    cases = []
    for path, subcommands, options, value_options in iter_command_tree(ctx.command, ctx):
        cases.append(
            f'        "{" ".join(path)}") '
            f'_gn_cmds="{" ".join(subcommands)}"; '
            f'_gn_opts="{" ".join(options)}"; '
            f'_gn_vopts="{" ".join(value_options)}" ;;'
        )
    return SCRIPT_TEMPLATE.format(cases="\n".join(cases))


def regenerate_completion_file():
    """
    Regenerate the completion file of the virtualenv, if any, in a new process
    so that newly installed commands (e.g. from a module) are taken into account.
    """
    completion_file = default_completion_file()
    if not completion_file.is_file():
        return
    click.echo("Mise à jour de l’autocomplétion…")
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "geonature.core.command",
            "generate-completion",
            "--output",
            str(completion_file),
        ],
    )
    if result.returncode != 0:
        click.secho(
            "Échec de la régénération de l’autocomplétion, "
            "relancez 'geonature generate-completion'.",
            fg="yellow",
            err=True,
        )


@main.command()
@click.option(
    "--output",
    "output_file",
    type=click.Path(dir_okay=False, path_type=Path),
    help=f"Fichier de sortie (par défaut : sortie standard). "
    f"Le fichier sourcé par le virtualenv est {default_completion_file()}",
)
@click.pass_context
def generate_completion(ctx, output_file):
    """
    Génère le script d’autocomplétion (bash et zsh) de la commande geonature.

    La liste des commandes est figée dans le script : il faut le régénérer
    après l’installation d’un module.

    Exemple :

    - geonature generate-completion --output "$VIRTUAL_ENV/bin/geonature_completion"
    """
    script = generate_completion_script(ctx.find_root())
    if output_file:
        output_file.write_text(script)
        click.echo(f"Script d’autocomplétion écrit dans {output_file}", err=True)
    else:
        click.echo(script, nl=False)
