name: "Build Sphinx Documentation"

on:
  push:
    branches:
      - master
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/iron

      - name: Build and Commit
        uses: sphinx-notes/pages@v3
        id: deployment
        with:
          requirements_path: docs/requirements.txt
          python_version: 3.11
          publish: false
        env:
          GEONATURE_CONFIG_FILE: config/test_config.toml

      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.deployment.outputs.artifact }}
